# Site settings
title: scott kilts
email: hello@scottkilts.com
description: > # this means to ignore newlines until "baseurl:"
  A simple portfolio theme meant to showcase written and visual content.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/

# Ruby Gems
gems:
  - jekyll-paginate
  - pygments
